sayings = [
    "Eat your carrots... they'll help you see in the dark.", 
    "Shut the door! Were you born in a barn?", 
    "Pull up your britches.", 
    "You need some meat on your bones.", 
    "Finish your food. Don't you know there are starving children in Africa?", 
    "Sit up straight.", 
    "Now don't spend it all in one place.",
    "More than you can shake a stick at.",
    "Use a little elbow grease.", 
    "Be sure to wash behind your ears.",
    "For Pete's sake!", 
    "She's no spring chicken.", 
    "Hand me my pocket book.", 
    "BINGO!", 
    "Don't do that, sweetie. Your face will stick that way.", 
    "Living in sin.", 
    "Have a seat on the davenport.", 
    "Do you need to piddle?", 
    "Oh my stars!", 
    "Quit fiddle fartin' around.", 
    "You need some patches on those pants.", 
    "Ain't ain't a word.", 
    "I wasn't born yesterday.", 
    "That's enough from the peanut gallery.", 
    "Who wants the gizzard?"
]